name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - run: dotnet build
    - run: dotnet publish ConwaysGameOfLife.csproj -c Release -o release --nologo
        
    # changes the base-tag in index.html from '/' to 'GameOfLifeBlazor' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to GameOfLifeBlazor
      run: sed -i 's/<base href="\/" \/>/<base href="\/GameOfLifeBlazor\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        BRANCH: gh-pages
        FOLDER: release/wwwroot
